### ISSUE TITLE
implement transport.Close()

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#176]
Once https://github.com/libp2p/go-libp2p/issues/999 is merged.

**Comment by Stebalien** [comment]
The upstream change has been merged. I believe we need to fix this sooner rather than later as it's causing testing issues.

**Comment by marten-seemann** [comment]
How exactly is it causing testing issues?

What exactly is `Close` supposed to do? Should all listeners be closed? Should all connections ever dialed from this transport be closed as well?

**Comment by Stebalien** [comment]
Sorry about that.

Due to our connection reuse logic, tests can oom and/or run out of file descriptors as we repeatedly start/stop libp2p nodes. Ideally, "Close" would close these reusable udp connections and block new ones from being created. We can also close all other connections, but that's not _required_.
