### ISSUE TITLE
Push the latest quic-go

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#33]
Currently, this doesn't build against the current quic-go. While we use gx internally, we prefer to keep everything building with `go get`. It's not *that* much of an issue here as QUIC is still experimental but it would be nice to be able to build with `go get`.

**Comment by marten-seemann** [comment]
I guess the problem here is that we're using the milestone version number in the `quic.Config`:
https://github.com/libp2p/go-libp2p-quic-transport/blob/8b63b936aaa0647dd406e52e2451d221756c147c/transport.go#L21-L32

Each milestone version number corresponds to a QUIC version number that is used in QUIC version negotiation. In quic-go, I'm only exposing milestone version numbers on tagged releases, to make sure that one version exactly corresponds to one snapshot of the code.
Considering that many changes I'm making to quic-go are breaking the compatibility with older versions, I don't see how we can make this work with `go get`.

**Comment by Stebalien** [comment]
Meh. This problem will disappear when QUIC stabilizes anyways.

**Comment by anacrolix** [comment]
This seems to be the only dep of ipfs that has this breaking behaviour. Is there anything that can be done?
