### ISSUE TITLE
Low max receive window

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#79]
The current max connection receive window is 4.5MiB. That limits the connection to ~240mbps (30MiB/s) given a 150ms RTT. Ideally, we'd be able to max out a gigabit link. Given that the actual window is adaptive and this is just the max, I'd suggest setting each _stream_ to a ~20MiB by default and the connection to 24MiB. (or something like that).

**Comment by marten-seemann** [comment]
The problem is that this opens a DoS opportunity. Given a sufficiently fast internet connection, it's easy to auto-tune the window to the maximum value, and then send stream data containing many gaps. Given how quic-go implements STREAM frame reassembly, this would allow an attacker to consume about 6x the memory of the window.

On the other hand, if an attacker is willing to invest the bandwidth to first auto-tune the window to the maximum value, he would also be able to establish multiple connections at the same time, thereby circumventing any limit we're setting here. Considering this, I think it wouldn't be too hazardous to increase the value. I suggest using the value that Linux uses for the maximum TCP receive window, which is 16 MB if I remember correctly.

**Comment by Stebalien** [comment]
16MiB is probably reasonable. We're not likely to get 1GiB cross country links (yet).

**Comment by marten-seemann** [comment]
Testing on various linux servers gives the same result:
```
❯ cat /proc/sys/net/ipv4/tcp_rmem
4096    131072  6291456
```
This is a 6 MB maximum receive window.

**Comment by Stebalien** [comment]
10MiB seems like a good middle ground. That's 100MiB/s on a 100ms latency. That's 1GiB/s on links with 10ms latencies (most places that care about _really fast_ throughput).
